//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVMultiplexProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking
    {
        public int bookingID { get; set; }
        public Nullable<int> showID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<System.DateTime> bookedDate { get; set; }
        public Nullable<System.DateTime> showDate { get; set; }
        public string seatTypeDesc { get; set; }
        public Nullable<int> noOfSeats { get; set; }
        public Nullable<int> foodID { get; set; }
        public Nullable<double> seatFare { get; set; }
    
        public virtual food food { get; set; }
        public virtual show show { get; set; }
        public virtual Useer Useer { get; set; }
    }
}
