//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVMultiplexProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MultiplexDBEntities : DbContext
    {
        public MultiplexDBEntities()
            : base("name=MultiplexDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<booking> bookings { get; set; }
        public virtual DbSet<food> foods { get; set; }
        public virtual DbSet<hall> halls { get; set; }
        public virtual DbSet<movie> movies { get; set; }
        public virtual DbSet<show> shows { get; set; }
        public virtual DbSet<Useer> Useers { get; set; }
    }
}
