//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DVMultiplexProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class show
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public show()
        {
            this.bookings = new HashSet<booking>();
        }
    
        public int showID { get; set; }
        public Nullable<int> hallID { get; set; }
        public Nullable<int> movieID { get; set; }
        public Nullable<int> slotNo { get; set; }
        public Nullable<System.DateTime> fromDate { get; set; }
        public Nullable<System.DateTime> toDate { get; set; }
        public Nullable<int> bookingID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking> bookings { get; set; }
        public virtual hall hall { get; set; }
        public virtual movie movie { get; set; }
    }
}
